### ISSUE TITLE
脚本跑不起来

### ISSUE THREAD

**Issue by lilydjwg** [wgjak47/WikiTranslationSpider#2]
```
ImportError: No module named WikiTranslationSpider.Spider
```

不小心了吧？

**Comment by wgjak47** [comment]
额，我在Mac和ubuntu上试的好像都正常啊。。。
Spider
<img width="563" alt="2015-09-15 9 23 44" src="https://cloud.githubusercontent.com/assets/7587180/9877553/214a9c38-5bf0-11e5-96e1-3c4adfa70bf9.png">
python -m 
<img width="570" alt="2015-09-15 9 28 53" src="https://cloud.githubusercontent.com/assets/7587180/9877654/ceba3162-5bf0-11e5-9ffc-02fa669095ee.png">

**Comment by lilydjwg** [comment]
你走安装然后再运行的流程试试？

**Comment by wgjak47** [comment]
就是安装后的啊。。。直接运行Spider命令或者python -m 都正常啊。运行环境？

**Comment by lilydjwg** [comment]
Arch Linux, Python 2.7.10.

奇怪。你删除了之前安装的版本什么的吗？我安装完成之后是一个  egg 文件，里边没有 `__init__.py` 所以报错了。

**Comment by wgjak47** [comment]
原因找到了，似乎跟setuptools有关系，我测试了OSX，Gentoo（Funtoo），Debian 7和ubuntu14.04四个环境，OSX和Debian 7可以正常使用，而Gentoo（Funtoo）和ubuntu14.04报错。原因是没加**init**.py.....Debian很神奇的为我自动添加**init**.py, 而OSX则给我打包成了一个二进制的egg。。。Orz。问题已修复。
